apiVersion: v1
kind: Pod
metadata:
  name: save
  labels:
    env : prod
    app : service
    tier : backend
    owner: sgKonovalov
spec:
  containers:
    - name: save
      image: sgkonovalov/save:latest